### PR TITLE
Confusing option in example...

### PR DESCRIPTION
**Pull request by plumpNation**
The requestAnimationFrame option isn't included in the options in the page, or in the master branch. I assume it is removed. I thought it would be better if it was removed from the example too.

### CODE REVIEW

**Comment by plumpNation** [comment]
The travis console output is a bit strange...

**Comment by skidding** [comment]
The option still exists, please check the source first: https://github.com/skidding/dragdealer/blob/master/src/dragdealer.js#L588-L599

It's just not documented. But your branch is pretty messed up, you merged branches a couple of times and ended up adding code from the `gh-pages` branch, so I'm closing this.

**Comment by plumpNation** [comment]
Apologies. Thanks for your reply.

**Comment by plumpNation** [comment]
Very sorry about my branches. Not intentional at all.

I just went back to the master branch now to check and could not find anywhere where the requestAnimationFrame option is used. In the example it is set to a boolean, as you know.

I'm clearly missing something, so I understand if you don't have the time to answer, I really appreciate the library and I'm finding it very useful.

**Pull request closed without merging**
